default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

docker: &docker
  <<: *default
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *docker
  database: app_development

test:
  <<: *docker
  database: app_test
